%----------------------------------------------------
%REPORT CONFIGURATIONS
%----------------------------------------------------

\LoadClass[a4paper,12pt,twoside]{article}
\ProvidesClass{Handout_kurama}

\usepackage[a4paper,margin=2.5cm]{geometry}
\usepackage{natbib}
\usepackage{amsmath, amssymb}
%\usepackage{pxfonts}
\usepackage{times}
%\usepackage{siunitx}
%\usepackage[normalem]{ulem}
\usepackage{type1cm}
%\usepackage{lineno}
%\usepackage[titletoc,title]{appendix}
\usepackage{graphicx}
\usepackage{color}
\usepackage[applemac]{inputenc}
\usepackage{mathtools}
%For Hyper refference
\usepackage[pdfstartview=FitH,%
  bookmarks=true,%
  bookmarksopen=true,%
  breaklinks=true,%
  colorlinks=true,%
  linkcolor=blue,anchorcolor=blue,%
  citecolor=blue,filecolor=blue,%
  menucolor=blue,%
  urlcolor=blue]{hyperref}
\usepackage{listings}
\usepackage{ascmac/tascmac}
\usepackage{amsthm}
\newtheorem{lemma}{Lemma}
